# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-23 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('mail', '男性'), ('femail', '女性')], max_length=8, verbose_name='匹配的性别')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳'), ('杭州', '杭州'), ('武汉', '武汉'), ('成都', '成都'), ('重庆', '重庆'), ('西安', '西安'), ('沈阳', '沈阳')], max_length=16, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查询范围')),
                ('max_distance', models.IntegerField(default=50, verbose_name='最大查询范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(verbose_name='开启震动')),
                ('only_matche', models.BooleanField(verbose_name='不让为匹配的人看我的相册')),
                ('auto_play', models.BooleanField(verbose_name='自动播放视频')),
            ],
        ),
    ]
